name: airline_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter

  # utility packages
  # http: ^1.2.1
  # intl: ^0.19.0
  # logger: ^2.3.0
  # url_launcher: ^6.3.0

  # icons
  # cupertino_icons: ^1.0.6
  # iconsax: ^0.0.8

  # state management

  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  persistent_bottom_nav_bar: ^5.0.2
  pinput: ^5.0.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/static/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 400

