name: airline_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:

  # icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #imaage
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1

  #Firebase
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0

  # utility packages
  http: ^1.2.2
  intl: ^0.19.0
  change_app_package_name: ^1.3.0

  # state management
  flutter_staggered_grid_view: ^0.7.0
  geolocator: ^11.1.0
  get: ^4.6.6
  get_storage: ^2.1.1

  #pickers
  country_picker: ^2.0.26
  intl_phone_number_input: ^0.7.4

  #Bars and indicators
  persistent_bottom_nav_bar: ^5.0.2
  smooth_page_indicator: ^1.1.0

  #Extras
  dotted_line: ^3.2.2
  pinput: ^5.0.0
  readmore: ^3.0.0

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/static/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 400
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 400

